id: a7484746-eaa5-4383-8604-2aa0a8622dd9
alias: TrackSensor_00_01
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.omjk_test_track_001
    from: "off"
    to: "on"
    id: "ON"
  - platform: state
    entity_id:
      - binary_sensor.omjk_test_track_001
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: "OFF"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: switch.omjk_test_track_led_01
      - conditions:
          - condition: trigger
            id: "OFF"
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.omjk_test_track_led_01
mode: single
