id: dcffcd4d-2fb1-439f-8906-e5174fcad310
alias: TrackSensor_00_02
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.omjk_test_track_002
    from: "off"
    to: "on"
    id: "ON"
  - platform: state
    entity_id:
      - binary_sensor.omjk_test_track_002
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: "OFF"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: switch.omjk_test_track_led_02
      - conditions:
          - condition: trigger
            id: "OFF"
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.omjk_test_track_led_02
mode: single
