id: c69966c8-5bc8-458e-809b-17ce1c5fb882
alias: TrackSensor_00_05
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.omjk_test_track_005
    from: "off"
    to: "on"
    id: "ON"
  - platform: state
    entity_id:
      - binary_sensor.omjk_test_track_005
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: "OFF"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: switch.omjk_test_track_led_05
      - conditions:
          - condition: trigger
            id: "OFF"
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.omjk_test_track_led_05
mode: single
