id: 2a391859-e705-4199-87c0-d02a97fd0230
alias: TrackSensor_01_06
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.futtog_00_06
    from: "off"
    to: "on"
    id: "ON"
  - platform: state
    entity_id:
      - binary_sensor.futtog_00_06
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: "OFF"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.trackoccupied_00_06
      - conditions:
          - condition: trigger
            id: "OFF"
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.trackoccupied_00_06
mode: single
