id: 98a3596d-a4cc-430b-a7c1-b3a293179965
alias: TrackSensor_001_003
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.omjk_test_track_003
    from: "off"
    to: "on"
    id: "ON"
  - platform: state
    entity_id:
      - binary_sensor.omjk_test_track_003
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: "OFF"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: switch.omjk_test_track_led_03
      - conditions:
          - condition: trigger
            id: "OFF"
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.omjk_test_track_led_03
mode: single
