substitutions:
  esphome_name: "omjk-test"

  id_hub0: "pcf8574_hub0"
  id_hub1: "pcf8574_hub1"
#  id_hub2: "pcf8574_hub2"
#  id_hub3: "pcf8574_hub3"
#  id_hub4: "pcf8574_hub4"
#  id_hub5: "pcf8574_hub5"
#  id_hub6: "pcf8574_hub6"
#  id_hub7: "pcf8574_hub7"

# PCF8574P & PCF8575
# 8bit portudvidelse I2C (2 wire) interface DIL16 Adresserbar til 
# hex:  0x20 0x21 0x22 0x23 0x24 0x25 0x26 0x27

# PCF8574AP
# 8bit portudvidelse I2C (2 wire) interface DIL16 Adresserbar til 
# hex: 0x38 0x39 0x3a 0x3b 0x3c 0x3d 0x3e 0x3f   

  addr_hub0: "0x20"
  addr_hub1: "0x21"
#  addr_hub2: "0x22"
#  addr_hub3: "0x23"
#  addr_hub4: "0x24"
#  addr_hub5: "0x25"
#  addr_hub6: "0x26"
#  addr_hub7: "0x27"

  i2c_sda: "21"
  i2c_scl: "22"
  i2c_scan: "true"
  i2c_id: "bus_a"

esphome:
  name: ${esphome_name}
  friendly_name: ${esphome_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_train

ota:
  password: !secret ota_pass_train

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_sekt
    password: !secret wifi_password_sekt

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esphome_name} Fallback Hotspot"
    password: !secret ap_password_train

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    bssid:
      name: "Connected BSSID"
    mac_address:
      name: "Mac Wifi Address"

button:
  - platform: restart
    name: "OMJK-test Restart"

i2c:
  sda: ${i2c_sda}
  scl: ${i2c_scl}
  scan: ${i2c_scan}  
  id: ${i2c_id}

# pcf8574P
# 8bit portudvidelse I2C (2 wire) interface DIL16 Adresserbar til 
# hex:  0x20 0x21 0x22 0x23 0x24  0x25 0x26 0x27

# pcf8574AP
# 8bit portudvidelse I2C (2 wire) interface DIL16 Adresserbar til 
# hex: 0x38 0x39 0x3a 0x3b 0x3c 0x3d 0x3e 0x3f   

pcf8574:
  - id: ${id_hub0} # Track-Sensor
    address: ${addr_hub0}
    pcf8575: false
  - id: ${id_hub1} # Track-Led
    address: ${addr_hub1}
    pcf8575: false
#  - id: ${id_hub2}
#    address: ${addr_hub2}
#    pcf8575: false
#  - id: ${id_hub3}
#    address: ${addr_hub3}
#    pcf8575: false
#  - id: ${id_hub4}
#    address: ${addr_hub4}
#    pcf8575: false
#  - id: ${id_hub5}
#    address: ${addr_hub5}
#    pcf8575: false

# Track-Sensor
# Individual input hub0
binary_sensor:
  - platform: gpio
    name: "Track #000"
    pin:
      pcf8574: ${id_hub0}
      number: 0
      mode:
        input: true
      inverted: true
    filters:
      - delayed_off: 100ms
  - platform: gpio
    name: "Track #001"
    pin:
      pcf8574: ${id_hub0}
      number: 1
      mode:
        input: true
      inverted: true
    filters:
      - delayed_off: 100ms
  - platform: gpio
    name: "Track #002"
    pin:
      pcf8574: ${id_hub0}
      number: 2
      mode:
        input: true
      inverted: true
    filters:
      - delayed_off: 100ms
  - platform: gpio
    name: "Track #003"
    pin:
      pcf8574: ${id_hub0}
      number: 3
      mode:
        input: true
      inverted: true
    filters:
      - delayed_off: 100ms
  - platform: gpio
    name: "Track #004"
    pin:
      pcf8574: ${id_hub0}
      number: 4
      mode:
        input: true
      inverted: true
    filters:
      - delayed_off: 100ms
  - platform: gpio
    name: "Track #005"
    pin:
      pcf8574: ${id_hub0}
      number: 5
      mode:
        input: true
      inverted: true
    filters:
      - delayed_off: 100ms
  - platform: gpio
    name: "Track #006"
    pin:
      pcf8574: ${id_hub0}
      number: 6
      mode:
        input: true
      inverted: true
    filters:
      - delayed_off: 100ms
  - platform: gpio
    name: "Track #007"
    pin:
      pcf8574: ${id_hub0}
      number: 7
      mode:
        input: true
      inverted: true

# Track-Led
# Individual output hub1
switch:
  - platform: gpio
    name: "Track-Led_00"
    pin:
      pcf8574: ${id_hub1}
      number: 0
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "Track-Led_01"
    pin:
      pcf8574: ${id_hub1}
      number: 1
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "Track-Led_02"
    pin:
      pcf8574: ${id_hub1}
      number: 2
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "Track-Led_03"
    pin:
      pcf8574: ${id_hub1}
      number: 3
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "Track-Led_04"
    pin:
      pcf8574: ${id_hub1}
      number: 4
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "Track-Led_05"
    pin:
      pcf8574: ${id_hub1}
      number: 5
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "Track-Led_06"
    pin:
      pcf8574: ${id_hub1}
      number: 6
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "Track-Led_07"
    pin:
      pcf8574: ${id_hub1}
      number: 7
      mode:
        output: true
      inverted: true
