# SSID & PASSWORD for local-wifi
wifi_ssid: "TP-LINK_9DD4"
wifi_password: "20230316"

wifi_ssid_sekt: "TP-Link_36A0"
wifi_password_sekt: "02485515"

# Secret for esp32 modeltog cpu
# Secure Password Generator: https://passwordsgenerator.net/
api_password: "tmdgs7eh6qpx69un99dxrgtad4uthtms"
ota_pass_train: "sg2fyndzekearezr4f8fcvt84zh3g6qs"
ap_password_train: "gzfn7gxf8nnnaruy"

api_key_train: "i9mYHwELFl+zpoNtXi4yAZNaA5zCMig+pf8k3a79Xvg="
