id: 90717a93-57cd-420c-b78b-20cffd713610
alias: TrackSensor_00_11
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.futtog_00_11
    from: "off"
    to: "on"
    id: "ON"
  - platform: state
    entity_id:
      - binary_sensor.futtog_00_11
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 1
    id: "OFF"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.trackoccupied_00_11
      - conditions:
          - condition: trigger
            id: "OFF"
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.trackoccupied_00_11
mode: single
