id: 71b9df82-95c8-4c2b-8467-ee87c466d682
alias: TrackSensor_00_15
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.futtog_00_15
    from: "off"
    to: "on"
    id: "ON"
  - platform: state
    entity_id:
      - binary_sensor.futtog_00_15
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 1
    id: "OFF"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.trackoccupied_00_15
      - conditions:
          - condition: trigger
            id: "OFF"
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.trackoccupied_00_15
mode: single
