id: 95eb53ee-0aef-457c-8e7e-54f892e795cf
alias: TrackSensor_00_12
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.futtog_00_12
    from: "off"
    to: "on"
    id: "ON"
  - platform: state
    entity_id:
      - binary_sensor.futtog_00_12
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 1
    id: "OFF"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.trackoccupied_00_12
      - conditions:
          - condition: trigger
            id: "OFF"
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.trackoccupied_00_12
mode: single
