id: 80ac9e7b-7ebe-4c31-a3e6-29e723b2c59c
alias: TrackSensor_00_16
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.futtog_00_16
    from: "off"
    to: "on"
    id: "ON"
  - platform: state
    entity_id:
      - binary_sensor.futtog_00_16
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 1
    id: "OFF"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.trackoccupied_00_16
      - conditions:
          - condition: trigger
            id: "OFF"
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.trackoccupied_00_16
mode: single
