# SSID & PASSWORD for local-wifi

wifi_ssid: "omjk2023"
wifi_password: "0123456789"

# API encryption, Enable transport encryption of the API layer.
# This is a 32-byte base64 encoded string. 
# Key Generator: https://esphome.io/components/api.html

api_key_train: "i9mYHwELFl+zpoNtXi4yAZNaA5zCMig+pf8k3a79Xvg="

# Secure Password Generator: https://passwordsgenerator.net/

ota_pass_train: "TjA2XG85YSmZa9QV"
ap_password_train: "4z3dT4dN8zJ3NX3b"
