substitutions:
  esphome_name: "futtog_001"

  id_hub0: "pcf8574_hub0"
  id_hub1: "pcf8574_hub1"
  id_hub2: "pcf8574_hub2"
  id_hub3: "pcf8574_hub3"
  id_hub4: "pcf8574_hub4"
  id_hub5: "pcf8574_hub5"

# PCF8574P & PCF8575
# 8bit portudvidelse I2C (2 wire) interface DIL16 Adresserbar til 
# hex:  0x20 0x21 0x22 0x23 0x24  0x25 0x26 0x27

# PCF8574AP
# 8bit portudvidelse I2C (2 wire) interface DIL16 Adresserbar til 
# hex: 0x38 0x39 0x3a 0x3b 0x3c 0x3d 0x3e 0x3f   

  addr_hub0: "0x21"
  addr_hub1: "0x38"
  addr_hub2: "0x39"
  addr_hub3: "0x3a"
  addr_hub4: "0x3b"
  addr_hub5: "0x3c"

  i2c_sda: "21"
  i2c_scl: "22"
  i2c_scan: "true"
  i2c_id: "bus_a"

esphome:
  name: ${esphome_name}
  friendly_name: ${esphome_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

dfplayer:
  on_finished_playback:
    then:
      logger.log: 'Playback finished event'

# Enable Home Assistant API
api:
  encryption:
    key: "yrHbKGxleerdoOctryNkCifXUUh8lSCgghYNISbhLHo="

  services:
  - service: dfplayer_next
    then:
      - dfplayer.play_next:
  - service: dfplayer_previous
    then:
      - dfplayer.play_previous:
  - service: dfplayer_play
    variables:
      file: int
    then:
      - dfplayer.play: !lambda 'return file;'
  - service: dfplayer_play_loop
    variables:
      file: int
      loop_: bool
    then:
      - dfplayer.play:
          file: !lambda 'return file;'
          loop: !lambda 'return loop_;'
  - service: dfplayer_play_folder
    variables:
      folder: int
      file: int
    then:
      - dfplayer.play_folder:
          folder: !lambda 'return folder;'
          file: !lambda 'return file;'

  - service: dfplayer_play_loop_folder
    variables:
      folder: int
    then:
      - dfplayer.play_folder:
          folder: !lambda 'return folder;'
          loop: true

  - service: dfplayer_set_device_tf
    then:
      - dfplayer.set_device: TF_CARD

  - service: dfplayer_set_device_usb
    then:
      - dfplayer.set_device: USB

  - service: dfplayer_set_volume
    variables:
      volume: int
    then:
      - dfplayer.set_volume: !lambda 'return volume;'
  - service: dfplayer_set_eq
    variables:
      preset: int
    then:
      - dfplayer.set_eq: !lambda 'return static_cast<dfplayer::EqPreset>(preset);'

  - service: dfplayer_sleep
    then:
      - dfplayer.sleep

  - service: dfplayer_reset
    then:
      - dfplayer.reset

  - service: dfplayer_start
    then:
      - dfplayer.start

  - service: dfplayer_pause
    then:
      - dfplayer.pause

  - service: dfplayer_stop
    then:
      - dfplayer.stop

  - service: dfplayer_random
    then:
      - dfplayer.random

  - service: dfplayer_volume_up
    then:
      - dfplayer.volume_up

  - service: dfplayer_volume_down
    then:
      - dfplayer.volume_down



ota:
  password: "f63e9344a092d132836ace8bb0a053c9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esphome_name} Fallback Hotspot"
    password: "mdZZqsXjd1nT"

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    bssid:
      name: "Connected BSSID"
    mac_address:
      name: "Mac Wifi Address"





i2c:
  sda: ${i2c_sda}
  scl: ${i2c_scl}
  scan: ${i2c_scan}  
  id: ${i2c_id}

pcf8574:
  - id: ${id_hub0}
    address: ${addr_hub0}
    pcf8575: false
  - id: ${id_hub1}
    address: ${addr_hub1}
    pcf8575: false
  - id: ${id_hub2}
    address: ${addr_hub2}
    pcf8575: false
  - id: ${id_hub3}
    address: ${addr_hub3}
    pcf8575: false
  - id: ${id_hub4}
    address: ${addr_hub4}
    pcf8575: false
  - id: ${id_hub5}
    address: ${addr_hub5}
    pcf8575: false

# Individual input hub0
binary_sensor:
  - platform: gpio
    name: "Track #000"
    pin:
      pcf8574: ${id_hub0}
      number: 0
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #001"
    pin:
      pcf8574: ${id_hub0}
      number: 1
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #002"
    pin:
      pcf8574: ${id_hub0}
      number: 2
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #003"
    pin:
      pcf8574: ${id_hub0}
      number: 3
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #004"
    pin:
      pcf8574: ${id_hub0}
      number: 4
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #005"
    pin:
      pcf8574: ${id_hub0}
      number: 5
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #006"
    pin:
      pcf8574: ${id_hub0}
      number: 6
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #007"
    pin:
      pcf8574: ${id_hub0}
      number: 7
      mode:
        input: true
      inverted: true

# Individual input hub1
# binary_sensor:
  - platform: gpio
    name: "Track #100"
    pin:
      pcf8574: ${id_hub1}
      number: 0
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #101"
    pin:
      pcf8574: ${id_hub1}
      number: 1
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #102"
    pin:
      pcf8574: ${id_hub1}
      number: 2
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #103"
    pin:
      pcf8574: ${id_hub1}
      number: 3
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #104"
    pin:
      pcf8574: ${id_hub1}
      number: 4
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #105"
    pin:
      pcf8574: ${id_hub1}
      number: 5
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #106"
    pin:
      pcf8574: ${id_hub1}
      number: 6
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #107"
    pin:
      pcf8574: ${id_hub1}
      number: 7
      mode:
        input: true
      inverted: true

# Individual input hub2
# binary_sensor:
  - platform: gpio
    name: "Track #200"
    pin:
      pcf8574: ${id_hub2}
      number: 0
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #201"
    pin:
      pcf8574: ${id_hub2}
      number: 1
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #202"
    pin:
      pcf8574: ${id_hub2}
      number: 2
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #203"
    pin:
      pcf8574: ${id_hub2}
      number: 3
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #204"
    pin:
      pcf8574: ${id_hub2}
      number: 4
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #205"
    pin:
      pcf8574: ${id_hub2}
      number: 5
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #206"
    pin:
      pcf8574: ${id_hub2}
      number: 6
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #207"
    pin:
      pcf8574: ${id_hub2}
      number: 7
      mode:
        input: true
      inverted: true

# Individual input hub3
# binary_sensor:
  - platform: gpio
    name: "Track #300"
    pin:
      pcf8574: ${id_hub3}
      number: 0
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #301"
    pin:
      pcf8574: ${id_hub3}
      number: 1
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #302"
    pin:
      pcf8574: ${id_hub3}
      number: 2
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #303"
    pin:
      pcf8574: ${id_hub3}
      number: 3
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #304"
    pin:
      pcf8574: ${id_hub3}
      number: 4
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #305"
    pin:
      pcf8574: ${id_hub3}
      number: 5
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #306"
    pin:
      pcf8574: ${id_hub3}
      number: 6
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #307"
    pin:
      pcf8574: ${id_hub3}
      number: 7
      mode:
        input: true
      inverted: true

# Individual input hub4
#binary_sensor:
  - platform: gpio
    name: "Track #400"
    pin:
      pcf8574: ${id_hub4}
      number: 0
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #401"
    pin:
      pcf8574: ${id_hub4}
      number: 1
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #402"
    pin:
      pcf8574: ${id_hub4}
      number: 2
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #403"
    pin:
      pcf8574: ${id_hub4}
      number: 3
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #404"
    pin:
      pcf8574: ${id_hub4}
      number: 4
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #405"
    pin:
      pcf8574: ${id_hub4}
      number: 5
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #406"
    pin:
      pcf8574: ${id_hub4}
      number: 6
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #407"
    pin:
      pcf8574: ${id_hub4}
      number: 7
      mode:
        input: true
      inverted: true

# Individual input hub5
# binary_sensor:
  - platform: gpio
    name: "Track #500"
    pin:
      pcf8574: ${id_hub5}
      number: 0
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #501"
    pin:
      pcf8574: ${id_hub5}
      number: 1
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #502"
    pin:
      pcf8574: ${id_hub5}
      number: 2
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #503"
    pin:
      pcf8574: ${id_hub5}
      number: 3
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #504"
    pin:
      pcf8574: ${id_hub5}
      number: 4
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #505"
    pin:
      pcf8574: ${id_hub5}
      number: 5
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #506"
    pin:
      pcf8574: ${id_hub5}
      number: 6
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Track #507"
    pin:
      pcf8574: ${id_hub5}
      number: 7
      mode:
        input: true
      inverted: true
