wifi_ssid: "abcdefghijklmn"
wifi_password: "12345678"

wifi_ssid_sekt: "abcdefghijklmnopq"
wifi_password_sekt: "12345678"

api_password: "tmdgs7eh6qpx69un99dxrgtad4uthtms"
ota_password: "sg2fyndzekearezr4f8fcvt84zh3g6qs"
ap_password: "gzfn7gxf8nnnaruy"

API-KEY-TRAIN: "i9mYHwELFl+zpoNtXi4yAZNaA5zCMig+pf8k3a79Xvg="
